### ISSUE TITLE
404 on downloading

### ISSUE THREAD

**Issue by shakeyourbunny** [K3VRAL/Itch.io-Bundle-Downloader#1]
Hi,

can you add some support for cookies or do a login to itch.io? 

Otherwise, the downloader never is able to get the games of the bundle.

**Comment by K3VRAL** [comment]
Hello!

From what I remember when making the script, cookies are used to use with `csfrToken` and when actually downloading the contents of the games. I used this script to download games without the use of logging in (where there was an option to purchase a bundle with or without an account, which I did without).

Maybe the use of an account has different properties to claim/download games? I can't really be sure since I don't have an account nor do I have access to an account with bought bundles.

I updated the script such that you can see what the script is doing so more information can be given in order to debug this issue with the new `-d` flag. I would recommend updating/git pulling the script and test it again. Try also putting the debug printing info here so maybe we can figure out whats going on.

**Comment by shakeyourbunny** [comment]
I already have rewritten the script in a big way that nearly nothing has been left alone.

My version now needs the cookies from a valid login in the Netscape cookies.txt format, parses the my purchases web page and grabs everything from there.

See https://github.com/shakeyourbunny/Itch.io-Bundle-Downloader

**Comment by shakeyourbunny** [comment]
It does its job now (currently downloading only games regardless of platform) with focus on getting all games of your account (and avoids redownloading already downloaded games). 

I was pondering to cut off the status as a fork, as it does not really share any code more, but your routines helped me much to understand how the itch.io download system works.

PS: it cannot do downloads from drive.google.com, dropbox or other stuff hiding behind the download links.

**Comment by shakeyourbunny** [comment]
Oh, one of the games who are using drive.google.com is https://honeycombinteractive.itch.io/spell-slingers-trick-or-treat-demo (part of the Ukraine bundle).

**Comment by K3VRAL** [comment]
Oh wow, yeah, you've rewritten everything! I can't really use it since I don't have an itch.io account, but looking at the code, I would be surprised if it didn't work, and I may just make an account, (if possible) link my Ukraine Bundle to the account, and trying this out.

It also seems a bit complicated to get things working, to be honest. I would like to (maybe) simplify your project, since it seems there are many steps to get things working (especially the cookies part by using browser scripts and making a text file etc) if that's ok with you (and put it in another branch in your repository for the time being).

I'll also investigate other websites and see how they are supported, maybe looking into drive, dropbox, or some other service that requires extra steps to get things working.

**Comment by K3VRAL** [comment]
Christ, I've severely pushed this project back when I see that I last looked into this. I guess now I can sort've say that it's rather complete in regard to the user login related stuff (you can use the flags or put your information in the environment file and python will just read from that), though I will need to do this without user login and may need to push this back for a while since I don't really have a bundle that is tied to an account.

> Oh, one of the games who are using drive.google.com is https://honeycombinteractive.itch.io/spell-slingers-trick-or-treat-demo (part of the Ukraine bundle).

And I finally did this, and it was a lot easier than I thought it would be (though I pushed this back).
